"""empty message

Revision ID: 42528a9bb195
Revises: e878ae5d4419
Create Date: 2023-09-30 17:21:01.150581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42528a9bb195'
down_revision = 'e878ae5d4419'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('passwordTable', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('passwordTable', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###
